//
// Generated file, do not edit! Created by opp_msgtool 6.3 from TaskMessage.msg.
//

#ifndef __TASKMESSAGE_M_H
#define __TASKMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TaskMessage;
/**
 * Class generated from <tt>TaskMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message TaskMessage
 * {
 *     int sourceId;
 *     int targetId;
 *     int subtaskId;
 * 
 *     // We can just pass the array chunk directly
 *     int arrayChunk[];
 * 
 *     // Flag to know if this message is sending the chunk or returning the max value
 *     bool isResult;
 *     int maxResult;
 * }
 * </pre>
 */
class TaskMessage : public ::omnetpp::cMessage
{
  protected:
    int sourceId = 0;
    int targetId = 0;
    int subtaskId = 0;
    int *arrayChunk = nullptr;
    size_t arrayChunk_arraysize = 0;
    bool isResult_ = false;
    int maxResult = 0;

  private:
    void copy(const TaskMessage& other);

  protected:
    bool operator==(const TaskMessage&) = delete;

  public:
    TaskMessage(const char *name=nullptr, short kind=0);
    TaskMessage(const TaskMessage& other);
    virtual ~TaskMessage();
    TaskMessage& operator=(const TaskMessage& other);
    virtual TaskMessage *dup() const override {return new TaskMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getTargetId() const;
    virtual void setTargetId(int targetId);

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual void setArrayChunkArraySize(size_t size);
    virtual size_t getArrayChunkArraySize() const;
    virtual int getArrayChunk(size_t k) const;
    virtual void setArrayChunk(size_t k, int arrayChunk);
    virtual void insertArrayChunk(size_t k, int arrayChunk);
    [[deprecated]] void insertArrayChunk(int arrayChunk) {appendArrayChunk(arrayChunk);}
    virtual void appendArrayChunk(int arrayChunk);
    virtual void eraseArrayChunk(size_t k);

    virtual bool isResult() const;
    virtual void setIsResult(bool isResult);

    virtual int getMaxResult() const;
    virtual void setMaxResult(int maxResult);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TaskMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TaskMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TaskMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<TaskMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASKMESSAGE_M_H

